### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by SpIdErPiGgY1984** [Crizz0/knowledgebase#18]
When adding an article

PHP 8.2.12
phpbb 3.3.11

`[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/log/log.php on line 264: Undefined array key "reportee_id"
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 1813: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3035)`

**Comment by Crizz0** [comment]
Hi,

what version of this extension do you use?

**Comment by SpIdErPiGgY1984** [comment]
> Hi,
> 
> what version of this extension do you use?

The latest
https://github.com/Crizz0/knowledgebase

**Comment by Crizz0** [comment]
k, thx. I can reproduce it. 

Will see, how to fix it. 

Regards

**Comment by SpIdErPiGgY1984** [comment]
Thank you 😁

**Comment by Crizz0** [comment]
> Thank you 😁

Pls try the changes in #19

**Comment by SpIdErPiGgY1984** [comment]
Problem solved! Thank you for the quick fix 😊
