### ISSUE TITLE
Warum keine TWIG-Syntax?

### ISSUE THREAD

**Issue by Mike-on-Tour** [Crizz0/knowledgebase#9]
https://github.com/Crizz0/knowledgebase/blob/05df7ac43d99d22f3f2120b72cc58a628bf16397/styles/prosilver/template/preview_article.html#L16

Hat es einen bestimmten Grund, warum du hier die alte phpBB-Syntax verwendet hast?

**Comment by Crizz0** [comment]
Nein, ist eher durchgerutscht.

Also genau genommen ist das so von dir und ich habs nicht angepasst, sondern nur den Präfix ergänzt.

**Comment by Mike-on-Tour** [comment]
Uups, dass das mein Versäumnis war, hatte ich jetzt nicht registriert.
